const express = require('express');
const router = express.Router();
const authenticateToken = require('../middleware/auth');
const pool = require('../db');
const multer = require('multer');
const path = require('path');

// Configure Multer to save files to api/src/uploads/
const upload = multer({ dest: path.join(__dirname, '../uploads/') });

// GET /items (Updated to fetch item_image)
router.get('/', async (req, res) => {
  let conn;
  try {
    conn = await pool.getConnection();
    let query = `
        SELECT i.item_id as id, u.usr_username as user, i.item_name as title,
               i.item_desc as description, l.loc_name as location,
               i.item_status as status, l.loc_lat as lat, l.loc_lon as lng,
               i.item_reply as reply, i.item_image as image
        FROM item i
        JOIN User_Items ui ON i.item_id = ui.USI_item_id
        JOIN User u ON ui.USI_usr_id = u.user_id
        LEFT JOIN Item_Location il ON i.item_id = il.IL_item_id
        LEFT JOIN Location l ON il.IL_loc_id = l.loc_id
        ORDER BY i.item_id DESC
    `;
    let params = [];
    
    if (req.query.user) {
        // ... (Keep your existing WHERE u.usr_username = ? query but add i.item_image as image) ...
        query = `
            SELECT i.item_id as id, u.usr_username as user, i.item_name as title,
                   i.item_desc as description, l.loc_name as location,
                   i.item_status as status, l.loc_lat as lat, l.loc_lon as lng,
                   i.item_reply as reply, i.item_image as image
            FROM item i
            JOIN User_Items ui ON i.item_id = ui.USI_item_id
            JOIN User u ON ui.USI_usr_id = u.user_id
            LEFT JOIN Item_Location il ON i.item_id = il.IL_item_id
            LEFT JOIN Location l ON il.IL_loc_id = l.loc_id
            WHERE u.usr_username = ?
            ORDER BY i.item_id DESC
        `;
        params.push(req.query.user);
    }
    
    const rows = await conn.query(query, params);
    const posts = rows.map(r => ({
        id: r.id,
        user: r.user,
        title: r.title,
        description: r.description,
        location: r.location || "Unknown Location",
        status: r.status,
        image: r.image, // Map the new image column
        coordinates: r.lat && r.lng ? { lat: parseFloat(r.lat), lng: parseFloat(r.lng) } : null,
        replies: r.reply ? [{ user: "Admin/Finder", text: r.reply }] : []
    }));

    res.status(200).json(posts);
  } catch (err) {
    res.status(500).json({error: "Database error"});
  } finally {
    if (conn) conn.release();
  }
});

// POST /items (Updated to use upload.single middleware)
router.post('/', authenticateToken, upload.single('image'), async (req, res) => {
  let conn;
  try {
    conn = await pool.getConnection();
    await conn.beginTransaction();
    
    const { title, description, location, status, lat, lng } = req.body;
    // req.file is generated by multer if an image was attached
    const imageFilename = req.file ? req.file.filename : null; 

    // Insert Item with image
    const itemResult = await conn.query(
        "INSERT INTO item (item_name, item_desc, item_status, item_image) VALUES (?, ?, ?, ?)",
        [title, description, status || "Lost", imageFilename]
    );
    const newItemId = Number(itemResult.insertId);

    // Link User to Item
    await conn.query(
        "INSERT INTO User_Items (USI_usr_id, USI_item_id) VALUES (?, ?)",
        [req.user.id, newItemId]
    );

    // Insert Location
    if (lat && lng && lat !== 'null' && lng !== 'null') {
        const locResult = await conn.query(
            "INSERT INTO Location (loc_name, loc_lat, loc_lon) VALUES (?, ?, ?)",
            [location || "Pinned Location", lat, lng]
        );
        await conn.query(
            "INSERT INTO Item_Location (IL_item_id, IL_loc_id) VALUES (?, ?)",
            [newItemId, Number(locResult.insertId)]
        );
    }

    await conn.commit();
    res.status(201).json({ message: "Item post created successfully!" });
  } catch (err) {
    if (conn) await conn.rollback();
    console.error(err);
    res.status(500).json({error: "Database error"});
  } finally {
    if (conn) conn.release();
  }
});

// PUT /items/:itemId/status
router.put('/:itemId/status', authenticateToken, async (req, res) => {
  let conn;
  try {
    conn = await pool.getConnection();
    await conn.query("UPDATE item SET item_status = ? WHERE item_id = ?", [req.body.status, req.params.itemId]);
    res.status(200).json({ message: "Status updated successfully", newStatus: req.body.status });
  } catch (err) {
    res.status(500).json({error: "Database error"});
  } finally {
    if (conn) conn.release();
  }
});

// POST /items/:itemId/replies (Protected)
router.post('/:itemId/replies', authenticateToken, async (req, res) => {
  let conn;
  try {
    conn = await pool.getConnection();
    await conn.query("UPDATE item SET item_reply = ? WHERE item_id = ?", [req.body.text, req.params.itemId]);
    res.status(201).json({ message: "Reply added successfully" });
  } catch (err) {
    res.status(500).json({error: "Database error"});
  } finally {
    if (conn) conn.release();
  }
});

module.exports = router;